"""Cutive Mono's outlines, translated to SVG paths, with lines running along the inside of each letter.

The outline is a straight translation of the typeface's own contours: each glyph's outline becomes the path data
type.js wants. TrueType stores curves as quadratics, and a quadratic has an exact cubic form, so every curve
converts without loss. Nothing is traced, thinned, fitted or approximated -- the shapes are the typeface's, to the
unit. Drawn with no fill, a pen follows each letter's outline (and the counters inside O, A, B and the rest, which
are their own contours).

The inside lines come from inside_data.py: one line down the middle of each stroke's channel, which is where the
two borders would meet if you thickened them inward. They stop short of the walls and never run alongside each
other, though they may cross and meet.

Needs fontTools:  pip3 install fonttools
Rebuild:          python3 tools/cutive.py > docs/cutive.js
"""
import os
import sys

from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import RecordingPen

from inside_data import INSIDE

FONT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'CutiveMono-Regular.ttf')

# the glyph space type.js draws in: baseline at y=58, cap top at y=4, so a cap-height letter is 54 tall
BASELINE = 58.0
CAP_TOP = 4.0
PLACES = 2          # decimals kept in the path data

LETTERS = [chr(c) for c in range(ord('A'), ord('Z') + 1)]
DIGITS = [chr(c) for c in range(ord('0'), ord('9') + 1)]
PUNCTUATION = list('$,."\'!:?#')


def key(ch):
    """The character as an object key: bare where js allows it, quoted otherwise."""
    if ch.isalnum():
        return ch
    return '"\'"' if ch == "'" else f"'{ch}'"


def num(v):
    s = f'{v:.{PLACES}f}'.rstrip('0').rstrip('.')
    return '0' if s in ('', '-0') else s


def outline_path(pen_value, to_glyph):
    """The recorded contours as one path. Quadratics become cubics exactly:
    c1 = p0 + 2/3 (q - p0), c2 = p3 + 2/3 (q - p3)."""
    out = []
    here = start = None

    def cubic(p0, q, p3):
        c1 = (p0[0] + 2 / 3 * (q[0] - p0[0]), p0[1] + 2 / 3 * (q[1] - p0[1]))
        c2 = (p3[0] + 2 / 3 * (q[0] - p3[0]), p3[1] + 2 / 3 * (q[1] - p3[1]))
        a, b, c = to_glyph(c1), to_glyph(c2), to_glyph(p3)
        out.append(f'C{num(a[0])} {num(a[1])} {num(b[0])} {num(b[1])} {num(c[0])} {num(c[1])}')

    for op, args in pen_value:
        if op == 'moveTo':
            here = start = args[0]
            p = to_glyph(here)
            out.append(f'M{num(p[0])} {num(p[1])}')
        elif op == 'lineTo':
            here = args[0]
            p = to_glyph(here)
            out.append(f'L{num(p[0])} {num(p[1])}')
        elif op == 'qCurveTo':
            pts = list(args)
            on, offs = pts[-1], pts[:-1]
            if on is None:
                # an all-offcurve contour: the last control point implies the start
                on = ((offs[0][0] + offs[-1][0]) / 2, (offs[0][1] + offs[-1][1]) / 2)
            for i, q in enumerate(offs):
                # consecutive control points imply an on-curve point halfway between them
                end = on if i == len(offs) - 1 else ((q[0] + offs[i + 1][0]) / 2, (q[1] + offs[i + 1][1]) / 2)
                cubic(here, q, end)
                here = end
        elif op == 'curveTo':
            *cs, end = args
            a, b, c = to_glyph(cs[0]), to_glyph(cs[1]), to_glyph(end)
            out.append(f'C{num(a[0])} {num(a[1])} {num(b[0])} {num(b[1])} {num(c[0])} {num(c[1])}')
            here = end
        elif op == 'closePath':
            out.append('Z')
            here = start
    return ''.join(out)


HEADER = '''// Cutive Mono (Google Fonts, SIL Open Font License), as single-line letters and as outlines.
//
// chars: one stroke down the middle of each part of a letter, drawn by hand over the outlines. This is the font
// for plotting -- a pen follows each line once, and the letters are joined up where their parts meet.
//
// outline: the typeface's own contours -- quadratics converted to their exact cubic form -- so the shapes are
// Cutive Mono's to the unit, not traced or fitted. With no fill, a pen follows each letter's border, and the
// counters inside O, A, B and the rest are their own closed contours.
//
// [path, width, yOffset] in a glyph space with the baseline at y=58 and the cap top at y=4, the same as the chars
// in type.js. Monospaced: every glyph is {width} wide. Generated by tools/cutive.py.
export const outline = {{'''

MIDDLE = '''}}

// the single lines, kept on their own so a drawing can show them with or without the borders
export const inside = {{'''

FOOTER = '''}}

// the single-line letters: what drawText draws
export const chars = Object.fromEntries(
  Object.entries(outline).map(([c, [, w, y]]) => [c, [inside[c] ?? 'M0 0', w, y]])
)

// how tall the glyphs run, in their own space
export const glyphHeight = 58

// every glyph's advance, since this one is monospaced (textWidth is just this times the string's length)
export const advance = {width}

// pass either of these to drawText and textBox in type.js as font
export const cutive = {{ chars, glyphHeight }}
export const cutiveOutline = {{ chars: outline, glyphHeight }}'''


def main():
    font = TTFont(FONT)
    cap = getattr(font['OS/2'], 'sCapHeight', 0) or 1171
    scale = (BASELINE - CAP_TOP) / cap
    cmap = font.getBestCmap()
    glyphset = font.getGlyphSet()

    def to_glyph(p):
        return (p[0] * scale, BASELINE - p[1] * scale)

    borders, insides, width = [], [], None
    for ch in LETTERS + DIGITS + PUNCTUATION:
        name = cmap[ord(ch)]
        pen = RecordingPen()
        glyphset[name].draw(pen)
        width = round(font['hmtx'][name][0] * scale, 1)
        borders.append(f"  {key(ch)}: ['{outline_path(pen.value, to_glyph)}', {width}, 0]")
        if INSIDE.get(ch):
            insides.append(f"  {key(ch)}: '{INSIDE[ch]}'")
    borders.append(f"  ' ': ['M0 0', {width}, 0]")

    print(HEADER.format(width=width))
    print(',\n'.join(borders) + ',')
    print(MIDDLE.format(width=width))
    print(',\n'.join(insides) + ',')
    print(FOOTER.format(width=width))


if __name__ == '__main__':
    if not os.path.exists(FONT):
        sys.exit(f'missing {FONT} -- the font file lives next to this script')
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    main()
